#!/usr/bin/env bash
set -e

# Location of your iTunes music library xml file.
# It shouldn't touch this, but back up just to be safe!
xml_location=~/Music/iTunes\ Library/iTunes\ Library.xml

# Location of your iTunes music media (actual music files)
# Must include final slash
music_location=~/Music/iTunes\ Media/Music/

# Location of where to store music on your Android device.
# Must include final slash.
# Make sure to run `pwd` in termux to get this - it's not the real
# SD card path!
android_music_path="/data/data/com.termux/files/home/storage/external-1/itunes/"



# Folder inside the $android_music_path folder to store music files
# (to keep separate from playlists).
music_folder="media"

# Folder inside the $android_music_path folder to store playlists.
playlists_folder="playlists"


############################

echo "android-itunes-rsync, Jake Coppinger 2019"
echo "https://github.com/jakecoppinger/android-itunes-rsync"
echo ""

# Generate playlists from iTunes
echo "Generating playlists from iTunes..."
java -jar iTunesExportScala-2.2.2/Itunesexport.jar -library="$xml_location" -outputDir=playlists/

# Rename paths in M3U playlist files to be relative
echo ""
echo "Generating playlists to be relative..."
sed -i '' "s?file://$music_location?../$music_folder/?g" playlists/*.m3u

# If using SSHelper, see https://arachnoid.com/android/SSHelper/ for notes on rsync quirks.
# Termux should allow all options.

# Be careful of the character sets - hence the iconv option.

# Sync playlists, delete old on remote.
echo ""
echo "Syncing playlists..."
rsync --human-readable -a --no-perms --size-only --partial  --info=progress2 --exclude=.DS_Store --iconv=utf-8-mac,utf-8 --delete  playlists/ phone:$android_music_path$playlists_folder

# Sync music, delete old on remote.
echo ""
echo "Syncing music..."
rsync  --human-readable -a --no-perms --size-only --partial  --info=progress2 --exclude=.DS_Store --iconv=utf-8-mac,utf-8 --delete "$music_location" phone:$android_music_path$music_folder/

# Delete temp exported playlists.
echo ""
echo "Deleting exported playlists..."
rm -rf playlists/

echo ""
echo "Done!"
